# This file contains values from Cookiecutter

default_context:
  project_name: "ls-exif"
  project_description: "An 'ls' companion displaying EXIF metadata columns"
  organization: "hheimbuerger"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "hheimbuerger"
  email: "henrik@heimbuerger.de"
  version: "1.0.0"
  line_length: "160"
  create_example_template: "cli"
